name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: drupal
          MYSQL_DATABASE: db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '7.4'
            drupal-core: '^9.4'
#          - php-version: '8.0'
#            drupal-core: '^9.5'
#          - php-version: '8.1'
#            drupal-core: '10.0.x-dev'
#          - php-version: '8.2'
#            drupal-core: '10.1.x-dev'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Setup Drupal action
        uses: bluehorndigital/setup-drupal@v1.0.4
        with:
          version: ${{ matrix.drupal-core }}
          dependencies: 'drupal/coder:=8.3.13'
      - name: Set coding standards path
        run: ~/drupal/vendor/bin/phpcs --config-set installed_paths /home/runner/drupal/vendor/drupal/coder/coder_sniffer
      - name: Workaround to install webform module
        run: cd ~/drupal && composer require drupal/webform
      - name: Checkout module
        uses: actions/checkout@v2
      - name: Copy module into drupal installation
        run: mkdir -p ~/drupal/web/modules/contrib && cp -ar ~/work/psu_webform_flood ~/drupal/web/modules/contrib
      - name: Check coding standards
        run: ~/drupal/vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,install,js ~/drupal/web/modules/contrib/psu_webform_flood
      - name: Run php built-in server
        run: php -S 127.0.0.1:8080 -t ~/drupal/web &
      - name: Run functional tests
        run: cd ~/drupal/web && \export SIMPLETEST_BASE_URL="http://127.0.0.1:8080" && export SIMPLETEST_DB="mysql://root:drupal@127.0.0.1:3306/db" && export SYMFONY_DEPRECATIONS_HELPER="999999" &&  ../vendor/bin/phpunit -c core modules/contrib/psu_webform_flood
